CREATE DATABASE IF NOT EXISTS utenti_db;

USE utenti_db;

CREATE USER IF NOT EXISTS ESLR@localhost IDENTIFIED BY 'mia_password';
GRANT SELECT, INSERT, UPDATE, DELETE ON utenti_db.* TO ESLR@localhost;
CREATE TABLE IF NOT EXISTS utenti (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL
);